### ISSUE TITLE
Class 'DependencyInjection\Container\ContainerInitializer' not found

### ISSUE THREAD

**Issue by dmolineus** [contao-community-alliance/dependency-container#5] opened 2013-12-16 20:12 UTC
I've got this error a couple of times when updating with the composer client.

`[16-Dec-2013 20:07:46 UTC] PHP Fatal error:  Class 'DependencyInjection\Container\ContainerInitializer' not found in composer/vendor/contao-community-alliance/dependency-container/contao/config/config.php on line 19`

**Comment by fritzmg** [comment] 2015-07-16 14:17
Why does this happen in the first place? I frequently run into this problem, when I transfer a Contao installation from one server to another. In all cases it was from a LAMP to a LAMP server. I even made a direct file comparison of both installations to ensure that it was an exact mirror, yet on the new server I get the error
```
Fatal error: Class 'DependencyInjection\Container\ContainerInitializer' not found in …/system/modules/core/library/Contao/System.php on line 126 
```
In other cases I was able to fix it by manually executing a composer update on the console, but in my current case I do not have access to a console unfortunately.

Creating a `.skip` files in `system/modules/dependency-container` does not really solve the problem, since there will be other errors due to the missing dependency-container apparently (e.g. from the Contao Font Awesome extension - and creating a `.skip` file in there does not get rid of those errors for some reason).

**Comment by discordier** [comment] 2015-07-16 15:22
The problem is, that your autoloader can not locate the file.
`composer dumpautoload` should be sufficient to solve the problem.

What versions do you have installed? the problem should not appear at all in Contao >3.2 as the hack is not needed anymore.

**Comment by fritzmg** [comment] 2015-07-16 15:25
> The problem is, that your autoloader can not locate the file.

Well the error message says, that the class cannot be found, which in turn means, that it was probably not loaded by any autoloader. But the file structure and the files themselves is completely the same.

> composer dumpautoload should be sufficient to solve the problem.

As I said, on the new server in question, console is not available.

> What versions do you have installed? the problem should not appear at all in Contao >3.2 as the hack is not needed anymore.

* Contao 3.2.21
* contao-community-alliance/composer-client 	0.15.2
* contao-community-alliance/composer-plugin 2.3.5
* contao-community-alliance/dependency-container 1.8.1

**Comment by discordier** [comment] 2015-07-16 15:41
The installations are really 100% binary indentical?
Can not say anything from here aside that I have not experienced the problem for a long time now.
When you have an installation where this happens, could you trace the autoloader?

**Comment by fritzmg** [comment] 2015-07-16 16:38
> The installations are really 100% binary indentical?

Well I am making a "rule based" comparison, which would show the character differences in files (with a fallback to a binary comparison), but I could make a complete binary comparison as well.



> When you have an installation where this happens, could you trace the autoloader?

Hm... how could I do that? I tried to debug it a little bit, but with all the different autoloaders (?) I have no idea where and how to begin.

**Comment by fritzmg** [comment] 2015-07-17 10:23
I have made a complete binary comparison of both installations, with the following result:

![bc](https://cloud.githubusercontent.com/assets/4970961/8745275/75d06496-2c7e-11e5-8977-6311b459e1cc.png)

And the binary difference for **all** of these files is just because of the mismatch in `EOL` characters, otherwise the content is exactly the same.

**Comment by fritzmg** [comment] 2015-07-20 13:27
Any ideas? The problem is, that I could fix it by manually disabling and deleting extensions, so that I can get into the backend again and execute a composer update there - but in this case not even that is possible for me, since the shared hosting environment still runs with PHP 5.3.3 -_-. Thus I have to rely on doing composer updates elsewhere and simply deploying the changes to the live server.

**Comment by fritzmg** [comment] 2015-07-20 22:05
Sorry, I noticed today, that the [\ContaoCommunityAlliance\Contao\Composer\Runtime::initialize()](https://github.com/contao-community-alliance/composer-client/blob/master/src/system/modules/!composer/src/Runtime.php#L87) function also has the PHP 5.3.4 minimum requirement check, which in turn means that nothing will be autoloaded on < PHP 5.3.4 (which is reasonable). That was the whole problem in my case.

(I don't know what happened in those other cases though.)

**Comment by discordier** [comment] 2015-07-20 22:21
Ah, so the problem is now fixed? It only was a problem of an out of date PHP version?

**Comment by fritzmg** [comment] 2015-07-20 22:21
Yep, sorry for the spam in this issue though ;)

**Closed** 2015-07-21 01:40 UTC
Labels: bug
